name: shorebird_tests
description: Shorebird's  Flutter customizations tests
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  archive: ^3.5.1
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  meta: ^1.15.0
  test: ^1.24.0
