import("//flutter/common/config.gni")

source_set("patch_cache") {
  sources = [
    "patch_cache.cc",
    "patch_cache.h",
    "patch_mapping.cc",
    "patch_mapping.h",
  ]

  deps = [
    "//flutter/fml",
    "//flutter/runtime:libdart",
  ]

  # For shorebird_report_launch_start() in updater.h
  # The include path "third_party/updater/library/include/updater.h" is relative
  # to //flutter/, which is already in the default include path.
  include_dirs = [ "//flutter" ]
}
